[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  CONTENTFUL_SPACE_ID = ""
  CONTENTFUL_API_TOKEN = ""
  CONTENTFUL_PREVIEW_TOKEN = ""

[build]
  publish = "public/"
  command = "npm run build"
