[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  CONTENTFUL_SPACE_ID = ""
  CONTENTFUL_API_TOKEN = ""
  CONTENTFUL_PREVIEW_TOKEN = ""

[build]
  publish = "public/"
  command = "echo '\n.github/' >> .gitignore && npm run build"
